Update index.js
fasterize/url-regex pull request #1
Opened 2018-07-12 10:41 UTC by jeromelachaud

Authorize http & https protocols only

2018-07-12 11:07 UTC, abarre requested changes

2018-07-12 11:07 UTC, abarre commented on index.js
> +	const protocol = `((http)?s?:?)(//)${opts.strict ? '' : '?'}`;
You could simplify it even more : `((https?:)?//)${opts.strict ? '' : '?'}`

2018-07-13 08:25 UTC, abarre approved these changes

2018-07-13 08:26 UTC, abarre commented
Do you want that I squash the commit or will you do afterward ?

2018-07-13 09:25 UTC, jeromelachaud commented
Fixes #2

2018-07-16 08:08 UTC, closed without merging